

defaults:
  -
    scope:
      path:""
      type:"pages"
    values:
      layout:"main"
  -
    scope:
      path:""
      type:"posts"
    values:
      layout:"post"

sass:
  sass_dir: _assets/_sass
  style: compressed

theme:
